---

- name: Install Slurm client
  ansible.builtin.package:
    name: "{{ __slurm_packages.client }}"
    state: "{{ 'latest' if slurm_upgrade else 'present' }}"

- name: Include config dir creation tasks
  ansible.builtin.include_tasks: _inc_create_config_dir.yml
  when: slurm_create_dirs

- name: Install log rotation configuration
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/slurm
    mode: 0644
  when: slurm_rotate_logs

- name: Install plugstack.conf
  ansible.builtin.template:
    src: "plugstack.conf.j2"
    dest: "{{ slurm_config_dir }}/plugstack.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - Restart slurmd
    - Restart slurmctld

- name: Check that slurm plugin dir exists
  ansible.builtin.file:
    path: "{{ slurm_config_dir }}/plugstack.conf.d/"
    state: directory
  notify:
    - Restart slurmd
    - Restart slurmctld

- name: Install slurm.conf
  ansible.builtin.template:
    src: "slurm.conf.j2"
    dest: "{{ slurm_config_dir }}/slurm.conf"
    owner: root
    group: root
    mode: 0444
  notify:
    - Restart slurmd
    - Restart slurmctld

- name: Include munge tasks
  ansible.builtin.include_tasks: munge.yml
  when: slurm_configure_munge
